[package]
name = "kobold-bit-buf"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>"]
description = "Bit-level serialization and deserialization of data"
license = "ISC"
edition = "2021"

[dependencies]
kobold-utils = { path = "../kobold-utils" }
