[package]
name = "kobold"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>"]
edition = "2021"

[dependencies.kobold-object-property]
path = "../kobold-object-property"
features = ["enable-option-guessing", "serde"]

[dependencies]
kobold-bcd = { path = "../kobold-bcd" }
kobold-client-sig = { path = "../kobold-client-sig" }
kobold-nav = { path = "../kobold-nav" }
kobold-poi = { path = "../kobold-poi" }
kobold-types = { path = "../kobold-types" }
kobold-utils = { path = "../kobold-utils" }
kobold-wad = { path = "../kobold-wad" }

byteorder = "1.4"
clap = { version = "4.3", features = ["derive"] }
env_logger = "0.10"
serde = "1"
serde_json = "1"

[target.'cfg(not(target_os = "windows"))'.dependencies]
tikv-jemallocator = "0.5"
